site_name: Codiumate

nav: 
  - 'index.md'
  - Installation:
    - 'installation/index.md'
  - Test Generation:
    - 'tests/index.md'
    # - What can I test?: 'tests/what-can-i-test.md'
    # - Supported Languages: 'tests/supported-languages.md'
    # - How to use: 'tests/how-to-use.md'
    # - Configuration: 'tests/configuration.md'
    # - Example Test: 'tests/example-test.md'
    # - Behaviors: 'tests/behaviors.md'
    # - Context Preview: 'tests/context.md'
    # - Running Tests: 'tests/running-tests.md'
  - Chat:
    - 'chat/index.md'
    - Choose your Context:
      - 'chat/context/index.md'
      - File Mode: 'chat/context/file-mode.md'
      - Workspace Mode: 'chat/context/workspace-mode.md'
      - Free Chat: 'chat/context/free-chat.md'
    - Commands:
      - 'chat/commands/index.md'
      - /ask: 'chat/commands/ask.md'
      - /docstring: 'chat/commands/docstring.md'
      - /enahnce: 'chat/commands/enhance.md'
      - /explain: 'chat/commands/explain.md'
      - /improve: 'chat/commands/improve.md'
      - /test-suite: 'chat/commands/test-suite.md'
      - /quick-test: 'chat/commands/quick-test.md'
      - /commit: 'chat/commands/commit.md'
      - /describe: 'chat/commands/describe.md'
      - /review: 'chat/commands/review.md'
      - /issues: 'chat/commands/issues.md'
      - /recap: 'chat/commands/recap.md'
      - /update-changelog: 'chat/commands/update-changelog.md'
      - /find-on-github: 'chat/commands/find-on-github.md'
    - Threads: 'chat/threads.md'
  - Guides:
    - 'guides/index.md'
    # - Open a PR with Codiumate: 'guides/open-pr.md'
    # - Generate tests for Python: 'guides/generate-tests-python.md'

theme:
  logo: assets/logo_.png
  favicon: assets/favicon.ico
  name: material
  features:
    - navigation.tabs
    - navigation.expand
    - navigation.path
    - navigation.top
    - navigation.tracking
    - navigation.indexes
    - search.suggest
    - search.highlight
    - content.tabs.link
    - content.code.annotation
    - content.code.copy
    - toc.integrate
    - content.tabs.link
  language: en
  language: en
  custom_dir: overrides
    
  palette:
    - media: "(prefers-color-scheme)"
      toggle:
        icon: material/brightness-auto
        name: Switch to light mode
    - media: "(prefers-color-scheme: light)"
      scheme: default
      toggle:
        icon: material/toggle-switch-off-outline 
        name: Switch to dark mode
      primary: custom
      accent: custom 
    - media: "(prefers-color-scheme: dark)"
      scheme: slate 
      toggle:
        icon: material/toggle-switch
        name: Switch to light mode    
      primary: custom
      accent: custom
    
    

plugins:
  - social
  - search

extra:
  generator: false
  social:
    - icon: fontawesome/brands/github
      link: https://github.com/Codium-ai
    - icon: fontawesome/brands/discord
      link: https://discord.com/invite/SgSxuQ65GF
    - icon: fontawesome/brands/youtube
      link: https://www.youtube.com/@Codium-AI
    - icon: fontawesome/brands/linkedin
      link: https://www.linkedin.com/company/codiumai
    - icon: fontawesome/brands/twitter
      link: https://twitter.com/CodiumAI
    - icon: fontawesome/brands/instagram
      link: https://www.instagram.com/codiumai/

extra_css:
  - css/custom.css

markdown_extensions:
  - pymdownx.highlight:
      anchor_linenums: true
  - pymdownx.inlinehilite
  - pymdownx.snippets
  - admonition
  - pymdownx.arithmatex:
      generic: true
  - footnotes
  - pymdownx.details
  - pymdownx.superfences
  - pymdownx.mark
  - attr_list
  - pymdownx.emoji:
      emoji_index: !!python/name:material.extensions.emoji.twemoji
      emoji_generator: !!python/name:materialx.emoji.to_svg
  - toc:
      title: On this page
      toc_depth: 3
      permalink: true
  - pymdownx.tabbed:
      alternate_style: true

copyright: |
  &copy; 2024 <a href="https://www.codium.ai/"  target="_blank" rel="noopener">CodiumAI</a>