name: ci
on:
  push:
    branches:
      - docs-context

jobs:
  update-docs-context:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.x'

      - name: Run build script
        run: python scripts/build_docs_context.py # this will create a .llm_context.txt file in repo-root/.llm_context.txt

      - name: Clone codium-proxy
        env:
          CODIUM_PROXY_TOKEN: ${{ secrets.CODIUM_PROXY_TOKEN }}
        run: |
          git clone https://x-access-token:$CODIUM_PROXY_TOKEN@github.com/Codium-ai/codium-proxy.git
          cd codium-proxy
          echo "Successfully cloned codium-proxy"
      - name: Print working directory and list files
        run: |
          pwd
          ls -la

      - name: Make updates to codium-proxy docs content
        working-directory: codium-proxy
        run: |
          pwd
          ls -la
          # write .llm_context content to documentation/docs_context.txt
          echo "$(cat ../.llm_context.txt)" > documentation/docs_context.txt
          git config --global user.name "github-actions[bot]"
          git config --global user.email "github-actions[bot]@users.noreply.github.com"
          git checkout -b update-docs-context-branch
          git add documentation/docs_context.txt
          git commit -m "Automated update to docs_context.txt"
  